from requests import HTTPError, Response

from splat.model import MergeRequest
from tests.source_control.github.base_test import BaseGithubSourceControlTest


class TestFindMatchingPr(BaseGithubSourceControlTest):
    def setUp(self) -> None:
        super().setUp()

    def test_create_new_pr_successfully_creates_pr(self) -> None:
        self.setup_mock_requests_post()

        pr_title = "Splat Dependency Updates"
        pr_description = "Automated pull request generated by Splat."
        branch_name = "feature-branch"

        # Execute the method
        result = self.github_platform.pr_handler.create_new_pr(
            pr_title, pr_description, branch_name, self.project, draft=False, timeout=30
        )

        # Verify that the result is a MergeRequest object with the correct values
        self.assertIsInstance(result, MergeRequest)
        self.assertEqual(result.title, pr_title)
        self.assertEqual(result.url, "http://github.com/pull/1")
        self.assertEqual(result.project_url, "http://github.com/repo")
        self.assertEqual(result.project_name, self.project.name_with_namespace)
        self.assertEqual(result.operation, "Pull Request Created on Github")

        # Verify that the logger was called with the correct messages
        self.assertTrue(
            self.mock_logger.has_logged(
                [
                    f"DEBUG: Creating new pull request for {self.project.name_with_namespace} with title: {pr_title}",
                    f"INFO: Pull Request created successfully for {self.project.name_with_namespace}: "
                    + "http://github.com/pull/1",
                ]
            )
        )

    def test_create_new_pr_raises_exception_on_failure(self) -> None:
        # Setup a failed response
        response = Response()
        response.status_code = 500
        response._content = b"Internal Server Error"
        self.mock_api._post_request_error = HTTPError(response=response)

        pr_title = "Splat Dependency Updates"
        pr_description = "Automated pull request generated by Splat."
        branch_name = "feature-branch"

        # Execute and verify exception is raised
        with self.assertRaises(Exception) as context:
            self.github_platform.pr_handler.create_new_pr(
                pr_title, pr_description, branch_name, self.project, draft=False, timeout=30
            )

        self.assertIn("Failed to create pull request", str(context.exception))
        self.assertIn("500 - Internal Server Error", str(context.exception))
